{
    'name': 'EWSETA EOL Asset Purchase',
    'version': '19.0.1.5.5',
    'category': 'Human Resources/Assets',
    'summary': 'Employee end-of-life asset purchase requests (public form, verification, approval, reservation)',
    'depends': [
        'website',
        'mail',
        'portal',
        'hr',
        'it_asset_management',
        'ewseta_procurement',
        'proc_cms',
    ],
    'data': [
        'security/groups.xml',
        'security/ir.model.access.csv',
        'security/rules.xml',
        'data/sequence.xml',
        'data/eol_policy_document_data.xml',
        'data/eol_policy_migrate.xml',
        'data/eol_policy_body_migrate.xml',
        'data/mail_template_otp.xml',
        'data/mail_template_confirmation.xml',
        'data/proc_cms_eol_nav.xml',
        'views/eol_asset_category_views.xml',
        'views/eol_policy_document_views.xml',
        'views/eol_config_views.xml',
        'views/eol_purchase_request_views.xml',
        'views/maintenance_equipment_views.xml',
        'views/eol_prepare_pool_wizard_views.xml',
        'views/eol_menus.xml',
        'views/website_eol_templates.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'ewseta_eol_asset_purchase/static/src/css/eol_backend.css',
        ],
        'web.assets_frontend': [
            (
                'after',
                'ewseta_procurement/static/src/css/rfq_theme.css',
                'ewseta_eol_asset_purchase/static/src/css/eol_website.css',
            ),
            'ewseta_eol_asset_purchase/static/src/js/eol_website.js',
        ],
    },
    'post_init_hook': 'post_init_hook',
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
    'author': 'EWSETA',
}
