# -*- coding: utf-8 -*-
{
    'name': 'EWSETA Website CMS',
    'version': '19.0.1.5.4',
    'category': 'Website/Website',
    'summary': 'Backend CMS for EWSETA public website content',
    'description': """
Manage EWSETA website content from the Odoo backend: hero slides, welcome
section, programme and sector cards, news, tenders, RFQs, and vacancies.
Role-based access for Marketing, HR, Supply Chain, and Website Administrators.
    """,
    'depends': [
        'ewseta_web',
        'website',
        'hr_recruitment',
        'website_hr_recruitment',
        'mail',
    ],
    'data': [
        'security/ewseta_cms_security.xml',
        'security/ir.model.access.csv',
        'data/sequence_data.xml',
        'data/ewseta_topbar_seed.xml',
        'data/ewseta_navbar_seed.xml',
        'data/ewseta_theme_seed.xml',
        'views/ewseta_website_topbar_views.xml',
        'views/ewseta_navbar_settings_views.xml',
        'views/ewseta_website_theme_views.xml',
        'views/ewseta_theme_settings_views.xml',
        'views/website_menu_views.xml',
        'views/ewseta_hero_slide_views.xml',
        'views/ewseta_home_welcome_views.xml',
        'views/ewseta_performance_metric_views.xml',
        'views/ewseta_programme_card_views.xml',
        'views/ewseta_sector_card_views.xml',
        'views/ewseta_news_article_views.xml',
        'views/ewseta_tender_views.xml',
        'views/ewseta_rfq_views.xml',
        'views/hr_job_views.xml',
        'views/ewseta_menus.xml',
        'views/website_templates.xml',
        'views/ewseta_topbar_template.xml',
        'views/ewseta_navbar_template.xml',
        'views/ewseta_whatsapp_template.xml',
        'views/ewseta_theme_template.xml',
        'views/ewseta_jobs_templates.xml',
        'views/snippets/s_ewseta_hero_carousel.xml',
        'views/snippets/s_ewseta_welcome.xml',
        'views/snippets/s_ewseta_performance.xml',
        'views/snippets/s_ewseta_programmes.xml',
        'views/snippets/s_ewseta_sectors.xml',
        'views/snippets/s_ewseta_news.xml',
    ],
    'post_init_hook': 'post_init_hook',
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
    'author': 'EWSETA',
}
