{
    "name": "EWSETA Procurement",
    "version": "19.0.1.0.54",
    "post_init_hook": "post_init_hook",
    "depends": ["base", "mail", "website", "proc_cms"],
    "data": [
        "security/groups.xml",
        "security/ir.model.access.csv",
        "security/rules.xml",
        "data/cron.xml",
        "data/sequence.xml",
        "data/website_branding.xml",
        "data/mail_templates.xml",
        "data/mail_templates_prov.xml",
        # "data/mail_privet_rfq_template.xml",
        "views/rfq_admin_views.xml",
        "views/rfq_views.xml",
        "views/submission_views.xml",
        "views/website_header_templates.xml",
        "views/website_footer_templates.xml",
        "views/website_theme_templates.xml",
        "views/website_landing_templates.xml",
        "views/website_contact_templates.xml",
        "views/website_rfq_templates.xml",
        "views/actions.xml",
        "views/menu.xml",
        "data/proc_cms_menu_cleanup.xml",
    ],

    "installable": True,
    "application": True,
    "assets": {
        "web.assets_backend": [
            "ewseta_procurement/static/src/css/rfq_backend.css",
        ],
        "web.assets_frontend": [
            "ewseta_procurement/static/src/css/rfq_theme.css",
            "ewseta_procurement/static/src/css/rfq_website_header.css",
            "ewseta_procurement/static/src/css/rfq_portal.css",
            "ewseta_procurement/static/src/css/rfq_landing.css",
            "ewseta_procurement/static/src/css/rfq_contact.css",
            "ewseta_procurement/static/src/css/rfq_footer.css",
            "ewseta_procurement/static/src/css/rfq_hover_animations.css",
            "ewseta_procurement/static/src/css/rfq_website_brand.css",
            "ewseta_procurement/static/src/js/rfq_portal_views.js",
            "ewseta_procurement/static/src/js/rfq_portal_datatable.js",
            "ewseta_procurement/static/src/js/rfq_landing.js",
            "ewseta_procurement/static/src/js/rfq_theme.js",
        ],
    },
}
