{
    'name': 'IT Assets Management',
    'version': '19.0.1.9.0',
    'category': 'Human Resources/Assets',
    'summary': 'Track organizational IT hardware — assign, maintain, and audit laptops, phones, and peripherals',
    'depends': ['hr_maintenance', 'maintenance', 'hr', 'mail'],
    'data': [
        'security/it_asset_security.xml',
        'security/ir.model.access.csv',
        'data/it_asset_sequence.xml',
        'data/it_incident_sequence.xml',
        'data/it_equipment_categories.xml',
        'data/it_asset_manufacturers.xml',
        'report/ewseta_report_layout.xml',
        'report/it_incident_report_template.xml',
        'report/it_incident_report.xml',
        'data/it_incident_mail_template.xml',
        'wizard/it_asset_incident_submit_wizard_views.xml',
        'wizard/it_asset_incident_approve_wizard_views.xml',
        'views/it_asset_incident_report_views.xml',
        'views/maintenance_equipment_views.xml',
        'views/hr_employee_views.xml',
        'views/hr_department_views.xml',
        'views/it_asset_assignment_views.xml',
        'views/it_asset_manufacturer_views.xml',
        'views/it_asset_category_views.xml',
        'views/it_asset_menus.xml',
        'security/it_asset_incident_security.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'it_asset_management/static/src/css/it_asset_backend.css',
        ],
        'web.report_assets_common': [
            'it_asset_management/static/src/css/ewseta_report.css',
        ],
    },
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
    'author': 'Custom',
}
